module.exports = {
	FIRE_BARRAGE : "FIRE_BARRAGE",
	LASER : "LASER",
	ROCKET : "ROCKET",
	SHIELD : "SHIELD",
	MATRIX : "MATRIX",
	MAGNET : "MAGNET",
	SCORE : "SCORE",
	STAR : "STAR",
	NONE : "NONE"
}
